/* Generated By:JJTree&JavaCC: Do not edit this line. GqdslParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GqdslParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 7;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 8;
  /** RegularExpression Id. */
  int HEX_LITERAL = 9;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 10;
  /** RegularExpression Id. */
  int OPEN1 = 11;
  /** RegularExpression Id. */
  int CLOSE1 = 12;
  /** RegularExpression Id. */
  int OPEN2 = 13;
  /** RegularExpression Id. */
  int CLOSE2 = 14;
  /** RegularExpression Id. */
  int SELECT = 15;
  /** RegularExpression Id. */
  int WHERE = 16;
  /** RegularExpression Id. */
  int COUNT = 17;
  /** RegularExpression Id. */
  int FILTER = 18;
  /** RegularExpression Id. */
  int DISTINCT = 19;
  /** RegularExpression Id. */
  int EDGE = 20;
  /** RegularExpression Id. */
  int PROPERTY = 21;
  /** RegularExpression Id. */
  int PROPERTY_VALUE = 22;
  /** RegularExpression Id. */
  int QUESTIONMARK = 23;
  /** RegularExpression Id. */
  int ALL = 24;
  /** RegularExpression Id. */
  int COLON = 25;
  /** RegularExpression Id. */
  int COMMA = 26;
  /** RegularExpression Id. */
  int START = 27;
  /** RegularExpression Id. */
  int END = 28;
  /** RegularExpression Id. */
  int QUERY = 29;
  /** RegularExpression Id. */
  int VAR = 30;
  /** RegularExpression Id. */
  int QUERY_VAR = 31;
  /** RegularExpression Id. */
  int JAVA_VAR = 32;
  /** RegularExpression Id. */
  int UNKNOWN = 33;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int INBRACES = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"SELECT\"",
    "\"WHERE\"",
    "\"COUNT\"",
    "\"FILTER\"",
    "\"DISTINCT\"",
    "<EDGE>",
    "<PROPERTY>",
    "<PROPERTY_VALUE>",
    "\"?\"",
    "\"*\"",
    "\":\"",
    "\",\"",
    "\"GQDSL_BEGIN\"",
    "\"GQDSL_END\"",
    "\"QUERY\"",
    "<VAR>",
    "<QUERY_VAR>",
    "<JAVA_VAR>",
    "<UNKNOWN>",
  };

}
