/* Generated By:JavaCC: Do not edit this line. GqdslParserTreeConstants.java Version 5.0 */
public interface GqdslParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTGRAPH = 1;
  public int JJTQUERYRETURN = 2;
  public int JJTQUERY = 3;
  public int JJTQUERYEXPR = 4;
  public int JJTSELECTVARS = 5;
  public int JJTWHEREPARAMS = 6;
  public int JJTPARAMLINE = 7;
  public int JJTRELATION = 8;
  public int JJTRELATIONVALUE = 9;


  public String[] jjtNodeName = {
    "Start",
    "Graph",
    "QueryReturn",
    "Query",
    "QueryExpr",
    "SelectVars",
    "WhereParams",
    "ParamLine",
    "Relation",
    "RelationValue",
  };
}
/* JavaCC - OriginalChecksum=0adb8970f93daf6154a8d531c0b7dbdd (do not edit this line) */
