/* Generated By:JJTree&JavaCC: Do not edit this line. GqdslParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GqdslParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int QUERY_START = 1;
  /** RegularExpression Id. */
  int JAVA_CODE = 2;
  /** RegularExpression Id. */
  int CONSTANT_VALUE = 8;
  /** RegularExpression Id. */
  int OPEN1 = 9;
  /** RegularExpression Id. */
  int OPEN2 = 10;
  /** RegularExpression Id. */
  int CLOSE2 = 11;
  /** RegularExpression Id. */
  int SELECT = 12;
  /** RegularExpression Id. */
  int WHERE = 13;
  /** RegularExpression Id. */
  int COUNT = 14;
  /** RegularExpression Id. */
  int FILTER = 15;
  /** RegularExpression Id. */
  int DISTINCT = 16;
  /** RegularExpression Id. */
  int EDGE = 17;
  /** RegularExpression Id. */
  int PROPERTY = 18;
  /** RegularExpression Id. */
  int PROPERTY_VALUE = 19;
  /** RegularExpression Id. */
  int QUESTION_MARK = 20;
  /** RegularExpression Id. */
  int ALL = 21;
  /** RegularExpression Id. */
  int COLON = 22;
  /** RegularExpression Id. */
  int DOT = 23;
  /** RegularExpression Id. */
  int IDENTIFIER = 24;
  /** RegularExpression Id. */
  int QUERY_VAR = 25;
  /** RegularExpression Id. */
  int JAVA_VAR = 26;
  /** RegularExpression Id. */
  int CLOSE1 = 27;
  /** RegularExpression Id. */
  int COMMA = 28;
  /** RegularExpression Id. */
  int UNKNOWN = 29;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int QUERY = 1;
  /** Lexical state. */
  int IN_BRACES = 2;
  /** Lexical state. */
  int STRING_BODY = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"QUERY\"",
    "<JAVA_CODE>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\\"\"",
    "<CONSTANT_VALUE>",
    "\"(\"",
    "\"{\"",
    "\"}\"",
    "\"SELECT\"",
    "\"WHERE\"",
    "\"COUNT\"",
    "\"FILTER\"",
    "\"DISTINCT\"",
    "<EDGE>",
    "<PROPERTY>",
    "<PROPERTY_VALUE>",
    "\"?\"",
    "\"*\"",
    "\":\"",
    "\".\"",
    "<IDENTIFIER>",
    "<QUERY_VAR>",
    "<JAVA_VAR>",
    "\")\"",
    "\",\"",
    "<UNKNOWN>",
  };

}
