/* Generated By:JJTree&JavaCC: Do not edit this line. GqdslParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GqdslParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int QUERY_START = 1;
  /** RegularExpression Id. */
  int CONSTANT_VALUE = 9;
  /** RegularExpression Id. */
  int OPEN1 = 10;
  /** RegularExpression Id. */
  int OPEN2 = 11;
  /** RegularExpression Id. */
  int CLOSE2 = 12;
  /** RegularExpression Id. */
  int SELECT = 13;
  /** RegularExpression Id. */
  int WHERE = 14;
  /** RegularExpression Id. */
  int COUNT = 15;
  /** RegularExpression Id. */
  int FILTER = 16;
  /** RegularExpression Id. */
  int DISTINCT = 17;
  /** RegularExpression Id. */
  int EDGE = 18;
  /** RegularExpression Id. */
  int PROPERTY = 19;
  /** RegularExpression Id. */
  int PROPERTY_VALUE = 20;
  /** RegularExpression Id. */
  int QUESTION_MARK = 21;
  /** RegularExpression Id. */
  int ALL = 22;
  /** RegularExpression Id. */
  int COLON = 23;
  /** RegularExpression Id. */
  int DOT = 24;
  /** RegularExpression Id. */
  int IDENTIFIER = 25;
  /** RegularExpression Id. */
  int QUERY_VAR = 26;
  /** RegularExpression Id. */
  int JAVA_VAR = 27;
  /** RegularExpression Id. */
  int CLOSE1 = 28;
  /** RegularExpression Id. */
  int COMMA = 29;
  /** RegularExpression Id. */
  int UNKNOWN = 30;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int QUERY = 1;
  /** Lexical state. */
  int IN_BRACES = 2;
  /** Lexical state. */
  int STRING_BODY = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"QUERY\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 6>",
    "<token of kind 7>",
    "\"\\\"\"",
    "<CONSTANT_VALUE>",
    "\"(\"",
    "\"{\"",
    "\"}\"",
    "\"SELECT\"",
    "\"WHERE\"",
    "\"COUNT\"",
    "\"FILTER\"",
    "\"DISTINCT\"",
    "<EDGE>",
    "<PROPERTY>",
    "<PROPERTY_VALUE>",
    "\"?\"",
    "\"*\"",
    "\":\"",
    "\".\"",
    "<IDENTIFIER>",
    "<QUERY_VAR>",
    "<JAVA_VAR>",
    "\")\"",
    "\",\"",
    "<UNKNOWN>",
  };

}
