/* Generated By:JavaCC: Do not edit this line. GqdslParserTreeConstants.java Version 5.0 */
public interface GqdslParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTQUERY = 1;
  public int JJTVOID = 2;
  public int JJTGRAPH = 3;
  public int JJTRETURN = 4;
  public int JJTQUERYEXPR = 5;
  public int JJTQUERYSELECT = 6;
  public int JJTQUERYWHERE = 7;
  public int JJTWHEREEXPR = 8;
  public int JJTRELATIONSUBJECT = 9;
  public int JJTRELATION = 10;
  public int JJTRELATIONVALUE = 11;


  public String[] jjtNodeName = {
    "Start",
    "Query",
    "void",
    "Graph",
    "Return",
    "QueryExpr",
    "QuerySelect",
    "QueryWhere",
    "WhereExpr",
    "RelationSubject",
    "Relation",
    "RelationValue",
  };
}
/* JavaCC - OriginalChecksum=ec81ae9e1d2e0dc3f49a23ccede6f2ec (do not edit this line) */
